// Code generated by mockery v2.20.0. DO NOT EDIT.

package dotenv

import mock "github.com/stretchr/testify/mock"

// MockDotEnver is an autogenerated mock type for the DotEnver type
type MockDotEnver struct {
	mock.Mock
}

type MockDotEnver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDotEnver) EXPECT() *MockDotEnver_Expecter {
	return &MockDotEnver_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields:
func (_m *MockDotEnver) Load() {
	_m.Called()
}

// MockDotEnver_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockDotEnver_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockDotEnver_Expecter) Load() *MockDotEnver_Load_Call {
	return &MockDotEnver_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockDotEnver_Load_Call) Run(run func()) *MockDotEnver_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDotEnver_Load_Call) Return() *MockDotEnver_Load_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDotEnver_Load_Call) RunAndReturn(run func()) *MockDotEnver_Load_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockDotEnver interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDotEnver creates a new instance of MockDotEnver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDotEnver(t mockConstructorTestingTNewMockDotEnver) *MockDotEnver {
	mock := &MockDotEnver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
